### ISSUE TITLE
Today I noticed a couple of bugs in your mod

### ISSUE THREAD

**Issue by Tommy-XL** [music-discussion/TownOfHost-Unofficial#5]
When the round started, the Child role started spamming letters (C) and because of this, the game started to lag a lot
![photo_2022-08-21_15-25-49](https://user-images.githubusercontent.com/104814436/185783923-8c2b8a72-8a82-4e66-a27e-f073716b7f70.jpg)

When Time Thief (Last) and Jackal remained in the game, after voting, a black screen appeared for all players
![photo_2022-08-21_16-20-05](https://user-images.githubusercontent.com/104814436/185784087-10f3b4cd-09ac-41ea-ac77-65bc194bee9a.jpg)

Silencer role doesn't seem to work at all
![photo_2022-08-21_15-00-38](https://user-images.githubusercontent.com/104814436/185784066-0e9bf5b1-8f7b-4da6-89a9-5711f86687a5.jpg)

And PlagueBearer role does not display infected players

**Comment by Tommy-XL** [comment]
I'll leave my logs here if needed.
[LogOutput.log](https://github.com/music-discussion/TownOfHost-Unofficial/files/9388781/LogOutput.log)

**Comment by Tommy-XL** [comment]
Looks like the bug with Child was fixed in version v3

**Comment by music-discussion** [comment]
Silencer just broke one day. I will fix it soon. As for TimeThief and Jackal, I am using the beta 3.0.0 source code. I have an idea on how to fix that. And yes, the Child bug was fixed in Version 3. And PlagueBearer does display infected people. Might not display to dead people, but it definitely displays to PlagueBearer.

**Comment by Tommy-XL** [comment]
Oh, I forgot to say that in PlagueBearer, infected people are shown only at the host, and for a player without a mod, the rhombus is not displayed
Although, I will need to check it again

**Comment by music-discussion** [comment]
hmm okay

**Comment by music-discussion** [comment]
I will check the code and see whats wrong.

**Comment by music-discussion** [comment]
I think I fixed the Silencer issue. Will hopefully be patched in v3.
